### ISSUE TITLE
Error using `onError` middleware with Hono Basic Auth

### ISSUE THREAD

**Issue by austinm911** [w3cj/stoker#8]
I'm not sure what exactly may be going on, but I'm getting this error locally (intermittently) and deployed. If you comment out onError it will deploy without the error.

```ts
const app = new Hono<AppBindings>()

app
	.use(pinoLogger())
	.notFound(notFound)
	.onError(onError)
	.use(
		'*',
		basicAuth({
			username: 'user',
			password: 'password',
		}),
	)
	.get('/', async (c) => {
		const testData = {
			key1: 'value1',
			time: new Date().toISOString(),
		}
		c.var.logger.info(testData, 'Test!')
		return c.json(testData, 200)
	})

export default {
	fetch: app.fetch,
}
```

Error
```
{"message":"","stack":"Error\n    at basicAuth2 (api.js:16629:11)\n    at dispatch (api.js:15526:23)\n    at api.js:15503:12\n    at api.js:15756:32\n    at Object.dispatch (api.js:15766:7)\n    at Object.fetch (api.js:15769:17)"}
```

**Comment by aaronlippold** [comment]
I think we should all take a moment to smile at that title

--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by w3cj** [comment]
Did you ever resolve this?

If not, try moving the notFound and onError calls as the last in the chain (after .use and .get)
